update

diff --git a/.dotfiles/zshrc b/.dotfiles/zshrc
--- a/.dotfiles/zshrc
+++ b/.dotfiles/zshrc
@@ -1,4 +1,12 @@
+# Task: add option
+export DISABLE_TERMUX_API_VAR=1
 # All in one ZSHRC
+export DISABLE_COLOR_VAR=0
+
+export DISABLE_FUNCTION_LOAD=0
+export DISABLE_ALIAS=0
+export DISABLE_EXPORT=0 # include deleting starship package
+if [[ $DISABLE_COLOR_VAR == 0 ]]; then
 echo "[*] Loading Colors..."
 # Reset
 COL_RESET='\033[0m'       # Text Reset
@@ -18,11 +26,11 @@ BBlack='\033[1;30m'       # Black
 BRed='\033[1;31m'         # Red
 BGreen='\033[1;32m'       # Green
 BYellow='\033[1;33m'      # Yellow
-BBlue='\033[1;34m'        # Blue
+BBlue='\0r3[1;34m'        # Blue
 BPurple='\033[1;35m'      # Purple
 BCyan='\033[1;36m'        # Cyan
 BWhite='\033[1;37m'       # White
-echo -e "[*] Sucessfully applied ${BYellow}Bold Colors${COL_RESET}"
+echo -e "[${Green}*${COL_RESET}] Sucessfully applied ${BYellow}Bold Colors${COL_RESET}"
 # Underline
 UBlack='\033[4;30m'       # Black
 URed='\033[4;31m'         # Red
@@ -32,7 +40,7 @@ UBlue='\033[4;34m'        # Blue
 UPurple='\033[4;35m'      # Purple
 UCyan='\033[4;36m'        # Cyan
 UWhite='\033[4;37m'       # White
-echo -e "[*] Sucessfully applied ${UYellow}Underline Colors${COL_RESET}"
+echo -e "[${Green}*${COL_RESET}] Sucessfully applied ${UYellow}Underline Colors${COL_RESET}"
 # Background
 bg_Black='\033[40m'       # Black
 bg_Red='\033[41m'         # Red
@@ -42,7 +50,7 @@ bg_Blue='\033[44m'        # Blue
 bg_Purple='\033[45m'      # Purple
 bg_Cyan='\033[46m'        # Cyan
 bg_White='\033[47m'       # White
-echo -e "[*] Sucessfully applied ${bg_White}${BYellow}Background Colors${COL_RESET}"
+echo -e "[${Green}*${COL_RESET}] Sucessfully applied ${bg_White}${BYellow}Background Colors${COL_RESET}"
 
 # High Intensity
 IBlack='\033[0;90m'       # Black
@@ -53,7 +61,7 @@ IBlue='\033[0;94m'        # Blue
 IPurple='\033[0;95m'      # Purple
 ICyan='\033[0;96m'        # Cyan
 IWhite='\033[0;97m'       # White
-echo -e "[*] Sucessfully applied ${IYellow}High Intensity Colors${COL_RESET}"
+echo -e "[${Green}*${COL_RESET}] Sucessfully applied ${IYellow}High Intensity Colors${COL_RESET}"
 # Bold High Intensity
 BIBlack='\033[1;90m'      # Black
 BIRed='\033[1;91m'        # Red
@@ -63,7 +71,7 @@ BIBlue='\033[1;94m'       # Blue
 BIPurple='\033[1;95m'     # Purple
 BICyan='\033[1;96m'       # Cyan
 BIWhite='\033[1;97m'      # White
-echo "[*] Sucessfully applied ${BIYellow}Bold High Intensity Colors${COL_RESET}"
+echo "[${Green}*${COL_RESET}] Sucessfully applied ${BIYellow}Bold High Intensity Colors${COL_RESET}"
 # High Intensity backgrounds
 bg_IBlack='\033[0;100m'   # Black
 bg_IRed='\033[0;101m'     # Red
@@ -73,7 +81,8 @@ bg_IBlue='\033[0;104m'    # Blue
 bg_IPurple='\033[0;105m'  # Purple
 bg_ICyan='\033[0;106m'    # Cyan
 bg_IWhite='\033[0;107m'   # White
-echo "[*] Sucessfully applied ${bg_IWhite}${UBlack}High Intensity Background Colors${COL_RESET}"
+echo "[${Green}*${COL_RESET}] Sucessfully applied ${bg_IWhite}${UBlack}High Intensity Background Colors${COL_RESET}"
+fi
 export ZSH="$HOME/.oh-my-zsh"
 
 CASE_SENSITIVE="false"
@@ -102,9 +111,8 @@ DISABLE_UNTRACKED_FILES_DIRTY="false"
 # man strftime
 # HIST_STAMPS="mm/dd/yyyy"
 
-echo "[*] Loading plugins..."
+echo "[${Blue}*${COL_RESET}] Loading plugins..."
 plugins=(
-  git
   zsh-autosuggestions
   zsh-syntax-highlighting
   command-time
@@ -120,38 +128,26 @@ ZSH_COMMAND_TIME_EXCLUDE=(vim mcedit)
 source $ZSH/oh-my-zsh.sh
 
 export ARCHFLAGS="-arch aarch64"
-echo "[*] Loading Termux API Variables"
+if [[ "$DISABLE_TERMUX_API_VAR" == 0 ]]; then
+echo "[${Yellow}*${COL_RESET}] Loading Termux API Variables"
 BATTERY_STATUS="$(termux-battery-status)"
 BATTERY_PERCENTAGE="$(jq -r .percentage <<< $BATTERY_STATUS)"
 WIFI_NETWORK="$(termux-wifi-connectioninfo)"
-
-
+termux-wake-lock
+fi
 # make new bash files for neovim and include bash shebang
-CRIS_NEWSHELL (){
-  echo '#!/data/data/com.termux/files/usr/bin/bash' > $1.sh
-  chmod +x $1.sh
-  $EDITOR $1.sh
-}
 # easy ping
+if [[ $DISABLE_FUNCTION_LOAD == 0 ]]; then
 CRIS_PINGFUNC (){
   if [[ $1 == "" ]]; then
     ping -c 10 -i 0.2 8.8.8.8
   else
     ping -c 10 -i 0.2 $1
-  fi
-}
-CRIS_RESETSSHD (){
-	termux-wake-lock
-	if [[ $1 == debug ]]; then 
-	  while true; do
-      sshd -dD | sleep 30000
-	  done
-  else
-	while true; do
-		sshd
-	done
 	fi
 }
+fi
+sshd && echo "[${Blue}*${COL_RESET}] Started SSH Agent" || echo "[${Red}*${Reset}] Failed to start SSH Agent"
+if [[ $DISABLE_ALIAS == 0 ]]; then
 echo "[*] Loading alias"
 alias zshrc="$EDITOR ~/.zshrc && omz reload"
 alias ohmyzsh="cd ~/.oh-my-zsh"
@@ -174,14 +170,19 @@ alias bashrc="eval $EDITOR $PREFIX/etc/bash.bashrc && bash"
 alias gcc15="clang-15"
 alias gcc16="clang-16"
 alias sl="sl -e"
-echo "[*] Exporting variable"
+alias vimrc="$EDITOR ~/.vimrc"
+alias dirvim="cd ~/.vim/"
+alias viminfo="cd ~/.viminfo/"
+fi
+if [[ $DISABLE_EXPORT == 0 ]]; then
+echo "[${Red}*${COL_RESET}] Exporting variable"
 export WHOAMI="$(whoami)"
 export USER="$WHOAMI"
 export ssh_config="$HOME/.ssh/config"
 export EDITOR="nvim"
 eval $(starship init zsh)
 clear
-
+fi
 echo -e "[${Green}*${COL_RESET}] Loaded .zshrc"
 if [[ $SSH_CONNECTION != "" ]]; then
   echo "===[ YOURE CONNECTING WITH SSH CONNECTION ]==="
@@ -198,6 +199,7 @@ echo """'     |         |       /~~\~~/
 \__|   |_)\__|   |\_/| |  \_/| \__//
 """ | lolcat
 fi
+if [[ "$DISABLE_TERMUX_API_VAR" == 1 ]];then echo "${Red}Battery percentage is disabled"; fi
 echo $BATTERY_PERCENTAGE 
 case $BATTERY_PERCENTAGE in
 	100) echo "${Yellow}Last battery percentage: ${BGreen}${BATTERY_PERCENTAGE}${Reset}";;
